AllCops:
  Include:
    - metadata.rb
    - Gemfile
    - attributes/**/*
    - recipes/**/*
    - libraries/**/*
    - providers/**/*
    - resources/**/*
      
  Exclude:
    - bin/**/*
    - test/**/*
    - vendor/**/*

Encoding:
  Exclude:
    - metadata.rb
    - Gemfile

LineLength:
  Enabled: false

Style/Next:
  Enabled: false

WordArray:
  MinSize: 3
