name              'dhcp'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs and configures DHCP'
chef_version      '>= 14.0'
source_url        'https://github.com/sous-chefs/dhcp'
issues_url        'https://github.com/sous-chefs/dhcp/issues'
version           '7.1.1'

supports 'debian'
supports 'ubuntu'
supports 'centos'
supports 'redhat'
supports 'fedora'
supports 'scientific'
supports 'oracle'
supports 'amazon'
